### ISSUE TITLE
iOS list items not highlighted on tap down in t95_ios_settings_page

### ISSUE THREAD

**Issue by ghunter99** [xster/flutter-test#1]
Hi @xster. I was just running your t95_ios_settings_page test (got to it from the link on the Flutter Preview 2 page) and noticed that list items do not get highlighted until after you tap down. Highlight should probably occur on the onTapDown gesture (and stop after onTapUp or onTapCancel). 
e.g. https://gist.github.com/ghunter99/d26ee729680b90b5c7fe0c5a131bfac0
Thanks for the great example.

**Comment by xster** [comment]
Thanks for pointing it out. We're going to fix it upstream.
